name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Node.js to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.JEROBAS_KEY }}

      - name: Remove path
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 ${{ secrets.JEROBAS_USER }}@${{ secrets.JEROBAS_HOST }} "rm -rf /home/${{ secrets.JEROBAS_USER }}/repos/lopoly-server"

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install and build locally
        run: |
          npm install
          npm run build

      - name: Copy to EC2
        run: |
          rsync -avz --delete \
            --exclude='src/***' \
            --exclude='node_modules' \
            --exclude='tsconfig.json' \
            --exclude='jest.config.js' \
            -e "ssh -o StrictHostKeyChecking=no -p 2222" \
            ./ ${{ secrets.JEROBAS_USER }}@${{ secrets.JEROBAS_HOST }}:/home/${{ secrets.JEROBAS_USER }}/repos/lopoly-server

      - name: Link persistent .env
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 ${{ secrets.JEROBAS_USER }}@${{ secrets.JEROBAS_HOST }} "
            ln -sf /home/${{ secrets.JEROBAS_USER }}/envs/.env.lopoly /home/${{ secrets.JEROBAS_USER }}/repos/lopoly-server/.env
          "

      - name: Setup and Deploy
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.JEROBAS_HOST }} 
           username: ${{ secrets.JEROBAS_USER }}
           key: ${{ secrets.JEROBAS_KEY }}
           port: 2222
           script: |
                source ~/.nvm/nvm.sh || true
                export PATH=$HOME/.nvm/versions/node/$(nvm version)/bin:$PATH
                cd /home/${{ secrets.JEROBAS_USER }}/repos/lopoly-server
                npm install
                pm2 delete lopoly-server || true
                pm2 start npm --name "lopoly-server" -- run start
