name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Node.js to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AWS_KEY }}

      - name: Remove path
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_HOST }} "rm -rf /home/ubuntu/lopoly-server"

      - name: Copy to EC2
        run: |
          rsync -avz --delete \
            --exclude node_modules \
            --rsync-path="mkdir -p /home/ubuntu/lopoly-server && rsync" \
            -e "ssh -o StrictHostKeyChecking=no" \
            . ubuntu@${{ secrets.AWS_HOST }}:/home/ubuntu/lopoly-server/

      - name: Link persistent .env
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_HOST }} "
            ln -sf /home/ubuntu/envs/.env.ls /home/ubuntu/lopoly-server/.env
          "

      - name: Run setup and deploy on EC2
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_HOST }} 'bash -l' << EOF 
              cd /home/ubuntu/lopoly-server
              source /home/ubuntu/.nvm/nvm.sh
              nvm use 22.9.0
              npm install

              # executa docker compose
              if ! docker ps -a --filter "name=postgres_db" --format '{{.Names}}' | grep -q "^postgres_db$"; then
                echo "Container 'postgres_db' não encontrado. Rodando docker-compose up..."
                docker-compose up -d
              else
                echo "Container 'postgres_db' já existe. Pulando docker-compose up."
              fi
              pm2 update
              npm run build

              /home/ubuntu/.nvm/versions/node/v22.9.0/bin/pm2 delete lopoly || true
              /home/ubuntu/.nvm/versions/node/v22.9.0/bin/pm2 start npm --name lopoly -- run start
          EOF
