name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Node.js to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.JEROBAS_KEY }}

      - name: Remove path
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 alfred@ec2-15-228-220-157.sa-east-1.compute.amazonaws.com "rm -rf /home/alfred/repos/lopoly-server"

      - name: Use Node.js 22.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0

      - name: Install and build locally
        run: |
          npm install
          npm run build

      - name: Copy to EC2
        run: |
          rsync -avz --delete \
           --exclude='src' \
           --exclude='node_modules' \
           --exclude='tsconfig.json' \
           --exclude='eslint.config.js' \
           -e "ssh -o StrictHostKeyChecking=no" \
           ./ ${{ secrets.JEROBAS_USER }}@${{ secrets.JEROBAS_HOST }}:/home/${{ secrets.JEROBAS_USER }}/repos/lopoly-server

      # - name: Link persistent .env
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ${{ secrets.JEROBAS_USER }}@${{ secrets.JEROBAS_HOST }} "
      #       ln -sf /home/ubuntu/envs/.env.ls /home/ubuntu/lopoly-server/.env
      #     "

      # - name: Run setup and deploy on EC2
      #   shell: bash
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_HOST }} 'bash -l' << EOF 
      #         cd /home/ubuntu/lopoly-server
      #         source /home/ubuntu/.nvm/nvm.sh
      #         nvm use 22.9.0
      #         npm install

      #         # executa docker compose
      #         if ! docker ps -a --filter "name=db_lopoly" --format '{{.Names}}' | grep -q "^db_lopoly$"; then
      #           echo "Container 'db_lopoly' não encontrado. Rodando docker-compose up..."
      #           docker-compose up -d --compatibility
      #         else
      #           echo "Container 'db_lopoly' já existe. Pulando docker-compose up."
      #         fi
      #         pm2 update

      #         /home/ubuntu/.nvm/versions/node/v22.9.0/bin/pm2 delete lopoly || true
      #         /home/ubuntu/.nvm/versions/node/v22.9.0/bin/pm2 start npm --name lopoly -- run start
      #     EOF
